name: pydrograph
channels:
- conda-forge
- defaults
dependencies:
- python
- ipython
- jupyter
- notebook
- ipykernel
- matplotlib
- numpy
- scipy
- pandas
- xmltodict
- fiona
- shapely
- pyproj>=2.0
- pip
- pip:
  - gis-utils

